
@startuml
!include renderer.puml
!include decoder.puml
!include player.puml
!include extractor.puml
!include stream.puml
!include mediasource.puml
!include datasource.puml
!include source_misc.puml

interface LoadControl
interface ControlDispatcher
interface PlaybackPreparer
interface MediaClock
abstract class Timeline


player <-- mediasource
player <-- renderer
mediasource <-- datasource
mediasource <-- mediaperiod
mediasource <-- extractor
mediaperiod <-- extractor
renderer <-- stream
renderer <-- decoder
chunk <-- datasource
@enduml