
@startuml


'Player
interface Player
interface ExoPlayer
abstract class BasePlayer
class SimpleExoPlayer

'Renderer
interface Renderer
interface RendererCapabilities
interface RenderersFactory
abstract class BaseRenderer
abstract class SimpleDecoderAudioRenderer
abstract class SimpleDecoderVideoRenderer
abstract class MediaCodecRenderer
class CameraMotionRenderer
class FfmpegAudioRenderer
class LibflacAudioRenderer
class LibvpxVideoRenderer
class LibvpxVideoRenderer
class LibvpxVideoRenderer
class MediaCodecAudioRenderer
class MediaCodecVideoRenderer
class MetadataRenderer
class TextRenderer
class DefaultRenderersFactory {
    createRenderers()
    buildVideoRenderers()
    buildAudioRenderers()
    buildTextRenderers()
    buildCameraMotionRenderers()
    buildMiscellaneousRenderers()
}

interface LoadControl
interface ControlDispatcher
interface PlaybackPreparer
interface MediaClock
abstract class Timeline

Player <-- ExoPlayer
Player <-- BasePlayer
BasePlayer <-- SimpleExoPlayer
ExoPlayer <-- SimpleExoPlayer

Renderer <-- BaseRenderer
RendererCapabilities <-- BaseRenderer
BaseRenderer <-- CameraMotionRenderer
BaseRenderer <-- SimpleDecoderAudioRenderer
SimpleDecoderAudioRenderer <--  FfmpegAudioRenderer
SimpleDecoderAudioRenderer <--  LibflacAudioRenderer
BaseRenderer <-- SimpleDecoderVideoRenderer
SimpleDecoderVideoRenderer <-- LibvpxVideoRenderer
BaseRenderer <-- MediaCodecRenderer
MediaCodecRenderer <-- MediaCodecAudioRenderer
MediaClock <-- MediaCodecAudioRenderer
MediaCodecRenderer <-- MediaCodecVideoRenderer
BaseRenderer <-- MetadataRenderer
BaseRenderer <-- TextRenderer
RenderersFactory <-- DefaultRenderersFactory


@enduml