
@startuml
!include renderer.puml
!include decoder.puml
!include player.puml
!include extractor.puml
!include stream.puml
!include mediasource.puml
!include datasource.puml
!include source_misc.puml
!include loadcontrol.puml
!include trackselection.puml
!include timeline.puml

interface ControlDispatcher
interface PlaybackPreparer
interface MediaClock


player <-- mediasource
player <-- renderer
player <-- loadcontrol
player <-- trackselection
mediasource <-- datasource
mediasource <-- mediaperiod
mediasource <-- timeline
mediasource <-- extractor
mediaperiod <-- extractor
renderer <-- stream
renderer <-- decoder
chunk <-- datasource
trackselection <-- bandwidthmeter
@enduml