@startuml

package Player
package MediaSource
package DataSource
package Renderer
package Stream
package Decoder
package Buffer
package MediaCodec
package MediaPeriod
package Extractor
package ExtractorInput

Player <-- MediaSource
Player <-- Renderer
MediaSource <-- DataSource
MediaSource <-- MediaPeriod
ExtractorInput <-- DataSource
Extractor <-- ExtractorInput
MediaPeriod <-- Extractor
Stream <-- MediaPeriod

Renderer <-- Stream
Renderer <-- Decoder
Renderer <-- MediaCodec
Decoder <-- Buffer
@enduml