
@startuml
'A media player interface defining traditional high-level functionality, such as the ability to play, pause, seek and query properties of the currently playing media.
package player {

interface Player
interface ExoPlayer
abstract class BasePlayer
class SimpleExoPlayer

Player <|-- ExoPlayer
Player <|-- BasePlayer
BasePlayer <|-- SimpleExoPlayer
ExoPlayer <|-- SimpleExoPlayer

}
@enduml